    @@grammar::CALC


    start = expression $ ;


    expression
        =
        | expression '+' term
        | expression '-' term
        | term
        ;


    term
        =
        | term '*' factor
        | term '/' factor
        | factor
        ;


    factor
        =
        | '(' expression ')'
        | real
        ;


   
    real 
    =
    |scientific
    |float
    |integer;
    
    scientific = /[0-9]*\.*[0-9]+[eEdD][+-]?[0-9]+/ ;
    
    float = /[0-9]*.[0-9]+/
    ;
    
    integer  = /\d+/
    ;
    

