    @@grammar::CALC


    start = expression $ ;


    expression
        =
        | lhs:expression binop:'+' ~ rhs:term
        | lhs:expression binop:'-' ~ rhs:term
        | term
        ;


    term
        =
        | lhs:term binop:'*' ~ rhs:factor
        | lhs:term binop:'/' ~ rhs:factor
        | factor
        ;


    factor
        =
        | '(' ~ @:expression ')'
        | '{' ~ @:expression '}'
	| integer
	| float
	;

    integer = /\d+/ 
	
    float
	=
	| /\d*\.\d+/ ;

